language: python

sudo: false

env:
    matrix:
        - CONDA_NPY=1.11  CONDA_PY=2.7
        - CONDA_NPY=1.11  CONDA_PY=3.4
        - CONDA_NPY=1.13  CONDA_PY=3.6

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
      wget ${MINICONDA_URL}/${MINICONDA_FILE}
      bash ${MINICONDA_FILE} -b
      export PATH=/home/travis/miniconda3/bin:$PATH
      conda update --yes conda

      conda create --yes -q -n test-environment python=$CONDA_PY numpy=%CONDA_NPY pytest
      source activate test-environment
      python setup.py install

script:
    - py.test tests

notifications:
    email: false
